### ISSUE TITLE
HTML file in campus-level view package being ignored on Sandbox

### ISSUE THREAD

**Issue by Steve-A-Orr** [dswalker/csu-central-package#3]
The _home_en_US.html_ file, in a campus-level view package, is being superceded by a file of the same name located in the Central Package. This is complicated by the fact that this _home_en_US.html_ has since been removed from the central code-base--but it is still causing issues. 

This can be confirmed or tested:

1. Modify the _home_en_US.html_ in a view package with some unique text content. 
2. Upload the new view package, per usual process, to **Primo Back Office**.
3. Select the "Inherit from Central Package" check-box.
4. Deploy the modifications. 
5. Notice the result will be a generic starting HTML page without your modifications. 
6. Now, de-select the "inherit" check-box and deploy again. 
7. You will now notice your unique content shows, confirming something in central package was causing conflict with campus-level HTML file.

The only conclusion I can think of is that the Primo system will only "overwrite" package files, not delete them, from the host application upon package upload. Therefore, since the HTML file was removed (and not uploaded) there exists a "ghost" file on the Primo hosting server which is affecting any campus who chooses to inherit from the central package.

If this conclusion is correct, then we must ask ExLibris to manually remove the offending _home_en_US.html_ file from their host. If it is not, then I can't imagine what the solution will be. I will shortly be making my first deployment on the Production Primo host--I'll update when I know if the problem exists there too or not.

**Comment by Steve-A-Orr** [comment]
Yes, the same problem is occurring in the Production environment. (...-primo.hosted.exlibrisgroup.com) 

Of course, if we want to customize the front-page content this means we cannot leverage the Central Package for our campus until it is resolved.

**Comment by dswalker** [comment]
This is scheduled to be fixed in May release (April 30): "For the new UI, changes made to the HTML in the local package did not override the Central Package when inheritance was enabled. This has been fixed."

**Comment by dswalker** [comment]
fixed in May release
