### ISSUE TITLE
Pseudo-full-text link should be eliminated

### ISSUE THREAD

**Issue by dswalker** [dswalker/csu-central-package#7]
Full-text availability status in full record display is green, masquerading as a link.  Should be the color of regular or text or hidden.

**Comment by Steve-A-Orr** [comment]
We've followed the suggestion, and CSS, provided in Basecamp a few weeks ago to alter the visual treatment so that it doesn't look like a link and our librarians are satisfied.

Of course, they all would prefer it actually be a usable link.

**Comment by dswalker** [comment]
Fixed in beta 2
