### ISSUE TITLE
List of (other) campus holdings should be collapsed 

### ISSUE THREAD

**Issue by dswalker** [dswalker/csu-central-package#8]
Users have little to no use to interact with other CSU holdings, and can be distracted by this information in the full record display.  Make it collapse-able instead.

**Comment by Steve-A-Orr** [comment]
Are you talking about the "GET IT FROM OTHER INSTITUTIONS" sub-section, under the "**In the Library**" section, when in an Item Detail view? (It seems to hold a "Show/Hide Libraries" button and a list of other CSU campuses with that item.)

If so, our campus is choosing to hide it using the following suggested CSS:
```prm-alma-more-inst { display: none; }```

**Comment by dswalker** [comment]
That's right, Steve.  That particular Show/Hide functionality that you see in place now is the feature mentioned here.
